workspace:
  base: /workdir
  path: rchain-perf-harness


services:
  bootstrap:
    image: rchain/rnode:dev
    detach: true
    commands:
      - /opt/docker/bin/rnode -c ./drone/config/bootstrap.toml run

  validator1:
    image: rchain/rnode:dev
    detach: true
    commands:
      - sleep 10
      - /opt/docker/bin/rnode -c ./drone/config/validator1.toml run

  push-metrics:
    image: cfmanteiga/alpine-bash-curl-jq
    detach: true
    commands:
      - cd metrics
      - /bin/bash loop-metrics.sh

pipeline:
  deploy:
    image: rchain/rnode:dev
    commands:
      - sleep 40
      - /opt/docker/bin/rnode --grpc-host validator1 --grpc-port 30015 deploy --from "0x1" --phlo-limit 0 --phlo-price 0 --nonce 0 drone/config/contracts/tut-philosophers.rho

  propose:
    image: rchain/rnode:dev
    commands:
      - /opt/docker/bin/rnode --grpc-host validator1 --grpc-port 30015 propose
  
  gatling:
    image: hseeberger/scala-sbt
    commands:
      - pwd
      - cd templater
      - sbt -Dhost=validator1 -Dport=30015 runner/gatling:test
