version: '3.1'

volumes:
    grafana_data_storage: {}

networks:
  metrics:
    external:
      name: perf_harness

services:
  grafana-ui:
    image: grafana/grafana:6.3.2
    networks:
      - metrics
    ports:
      - 13000:3000
    env_file:
      - ./grafana/grafana.conf
    volumes:
      - /var/lib/grafana:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/

  influxdb:
    image: influxdb:1.7.7
    networks:
      - metrics
    ports:
      - 8090:8090/udp
      - 8091:8091/udp
    volumes:
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
      - /var/lib/influxdb:/var/lib/influxdb
      - /tmp/influxdb:/tmp
