version: '2'

services:
  drone-server:
    image: drone/drone:0.8
    networks:
      - rchain-perf-harness_metrics
    ports:
      - 8080:8000
      - 9000
    volumes:
      - /var/lib/drone:/var/lib/drone/
    restart: always
    environment:
      - DRONE_OPEN=false
      - DRONE_ADMIN=lukasz-golebiewski
      - DRONE_ORGS=lukasz-golebiewski-org
      - DRONE_HOST=${DRONE_HOST}
      - DRONE_GITHUB=true
      - DRONE_GITHUB_CLIENT=${DRONE_GITHUB_CLIENT}
      - DRONE_GITHUB_SECRET=${DRONE_GITHUB_SECRET}
      - DRONE_SECRET=${DRONE_SECRET}
      - DRONE_NETWORK=rchain-perf-harness_metrics

  drone-agent:
    image: drone/agent:0.8
    networks:
      - rchain-perf-harness_metrics
    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=${DRONE_SECRET}

networks:
  rchain-perf-harness_metrics: