# config file version
apiVersion: 1

# list of datasources to insert/update depending
# whats available in the database
datasources:
- name: perf-harness
  type: influxdb
  access: proxy
  database: rnode
  url: http://influxdb:8086
  isDefault: false
  editable: true
  orgId: 1

- name: testnet1
  type: influxdb
  access: proxy
  database: testnet1
  url: http://influxdb:8086
  isDefault: false
  editable: true
  orgId: 1

- name: devnet
  type: influxdb
  access: proxy
  database: devnet
  url: http://influxdb:8086
  isDefault: false
  editable: true
  orgId: 1

- name: devnet2
  type: influxdb
  access: proxy
  database: devnet2
  url: http://influxdb:8086
  isDefault: false
  editable: true
  orgId: 1
